# Generated by Django 5.0.2 on 2025-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
