# Generated by Django 4.2.20 on 2025-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_sponsorise_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturelocation',
            name='distance',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
