# Generated by Django 4.2.20 on 2025-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_voiturelocation_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiturelocation',
            name='distance',
        ),
        migrations.AddField(
            model_name='voiturevendu',
            name='distance',
            field=models.CharField(default='0', max_length=50),
        ),
                migrations.AddField(
            model_name='voiturevendu',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
