# Generated by Django 4.2.20 on 2025-04-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_voiturelocation_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiturevendu',
            name='description',
        ),
    ]
