# Generated by Django 4.2.20 on 2025-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_voiturevendu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiturevendu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
